# Elasticsearch server
elasticsearch: 
  # host where Elasticsearch server is running
  host: "127.0.0.1"
  # port on which Elasticsearch server is listening
  port: 9200

# Corpus to use
corpus:
  # name of the Elasticsearch index where the corpus is stored
  index: "gluten_products"
  # name of the Elasticsearch document type where the corpus is stored
  type: "product"
  # list of document fields to generate phrases from
  fields: ["name","category","description"]

# Processors (add custom processors to list of modules)
processor:
  # name of the Elasticsearch index where annotated text is stored by the processors
  index: "gluten_products__annotated"
  # name of the Elasticsearch document type where annotated text is stored by the processors
  type: "product"
  # list of processor modules
  modules:
      # standard bayzee processor to POS tag english text
      # name of the prcessor
    - name: "pos_processor"
      # path to the python module (relative to the location of this config file)
      path: "../lib/pos-processor.py"
      # features that this processor extracts
      features:
        - name: "pos_tags"
          is_numerical: False
        - name: "first_pos_tag"
          is_numerical: False
        - name: "middle_pos_tag"
          is_numerical: False
        - name: "last_pos_tag"
          is_numerical: False
        - name: "avg_word_length"
          is_numerical: True
        - name: "non_alpha_chars"
          is_numerical: True

# Generation
generator:
  # training set file path (relative to the location of this config file)
  training_phrases_file_path: "training-phrases.csv"
  # hold-out set file path (relative to the location of this config file)
  hold_out_phrases_file_path: "hold-out-phrases.csv"
  # maximum number of words in generated phrase
  max_shingle_size: 3
  # minimum number of words in generated phrase
  min_shingle_size: 2
  # list of document's fields to generate phrases from
  fields: ["name","category","description","manufacturer"]
  # list of features to extract
  features:
    - name: "doc_count"
      is_numerical: True
    - name: "max_term_frequency"
      is_numerical: True
    - name: "avg_term_frequency"
      is_numerical: True
    - name: "max_score"
      is_numerical: True
    - name: "avg_score"
      is_numerical: True
  # precision of numerical features
  float_precision: 4

# output directory (relative to the location of this config file)
output_path: "../data"